# Usa la imagen base de MySQL
FROM mysql:latest

# Configura la contraseña de root de MySQL
ENV MYSQL_ROOT_PASSWORD=mi-contraseña

# Opcional: puedes incluir comandos adicionales para configurar la base de datos
# image:remi container:remi  
